name: Functions Integration

on:
  pull_request:
    branches: 
      - master
    paths:
      - 'functions/**'

jobs:
  lint_functions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: npm ci
        working-directory: functions

      - name: Lint Functions
        run: npm run lint
        working-directory: functions
