name: Website Integration

on:
  pull_request:
    branches: 
      - master
    paths:
      - 'website/**'

jobs:
  test_hugo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.73.0'
          extended: true

      - name: Install Dependencies
        run: npm ci
        working-directory: website

      - name: Build Website
        run: npm run build
        working-directory: website
